apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  labels:
    app.kubernetes.io/name: flask-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
        app.kubernetes.io/name: flask-app
    spec:
      containers:
        - name: flask-app-container
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - containerPort: 5000

          env:
            - name: SQLALCHEMY_DATABASE_URI
              value: "{{ .Values.env.database_url }}"

            - name: SECRET_KEY
              value: "{{ .Values.env.secret_key }}"

          
          livenessProbe:
            httpGet:
              path: /api/health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /api/health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5